### ISSUE TITLE
Could it deal with continuous outcome efficiently?

### ISSUE THREAD

**Issue by hedongyan** [zecevic-matej/iSPN#1]
Hello, Matej. I found that NCM algorithm of Xia etc need training many times if we want to get intervention density of outcome for same treatment variables. If outcome is continuous, we will need infinite networks. Could iSPN deal with this problem?

**Comment by zecevic-matej** [comment]
Yes, iSPN can deal with continuous variables. In fact, since we usually deploy Gaussian Leaf nodes, this is very natural and the standard choice of modelling. The setting to NCM is different, however, since iSPN will assume interventional data (as they are not parameterized SCMs but rather "partial" neural-causal model).

**Comment by hedongyan** [comment]
Thanks for the kind reply. I read your paper and code. However, I'm not very familar with SPN. It's still hard for me to understand that why sum and product with a non-parametric function approximator can calculate intergration and any marginal, such as \int p(y,w|x,z) p(y) d(x,y) and \int p(x,y,z) p(x) d(x), from leaf nodes. Is single leaf node distribution of single variable? Why the marginal or intergration on continues variables be tractable? It seems that calculate marginal and intergration will need infinite sum and product operations for all potential values of (x,y) or (x) and the sample number maybe not enough to estimate marginal accurately the due to high dimension.

**Comment by zecevic-matej** [comment]
Please consider for instance this lecture by P. Poupart (https://www.youtube.com/watch?v=Nm0jNqOnQ2o) it will help you get started with SPN. Also, consider SPFlow from Molina et al. (https://github.com/SPFlow/SPFlow) to get your hands-on and learn practically. Then I believe you'll have an easier time trying what you intended for now.

**Comment by hedongyan** [comment]
Many thanks~
